#!/bin/bash
# 
# RUN THIS SCRIPT ONLY WITH 'sudo' !
#
#@author: PROF. DIPL.-INF. DR. XAVIER NOUNDOU

set +x

#YERITH_HTTP_DEBIAN_REPO=http://127.0.0.1/debian

YERITH_VAR_WWW_HTML_DEBIAN_REPO=/var/www/html/debian

YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR=dists/bullseye/main/binary-all

YERITH_BULLSEYE_AMD64_PACKAGE_DIR=dists/bullseye/main/binary-amd64

YERITH_PACKAGE_DIR=dists/bullseye/main/binary-i386

YERITH_ERP_SYSTEM_DAEMON_BULLSEYE_AMD64_PACKAGE_DIR_FULL_PATH="${YERITH_VAR_WWW_HTML_DEBIAN_REPO}/${YERITH_BULLSEYE_AMD64_PACKAGE_DIR}"

YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR_FULL_PATH="${YERITH_VAR_WWW_HTML_DEBIAN_REPO}/${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR}"

YERITH_BULLSEYE_AMD64_PACKAGE_DIR_FULL_PATH="${YERITH_VAR_WWW_HTML_DEBIAN_REPO}/${YERITH_BULLSEYE_AMD64_PACKAGE_DIR}"

YERITH_BULLSEYE_I386_PACKAGE_DIR_FULL_PATH="${YERITH_VAR_WWW_HTML_DEBIAN_REPO}/${YERITH_PACKAGE_DIR}"


GZIP="gzip "

MKDIR="mkdir "

RM="rm "

CP="cp -r "

${RM} -rf ${YERITH_VAR_WWW_HTML_DEBIAN_REPO}

${MKDIR} -p ${YERITH_VAR_WWW_HTML_DEBIAN_REPO}

${MKDIR} -p "${YERITH_BULLSEYE_AMD64_PACKAGE_DIR_FULL_PATH}"

${MKDIR} -p "${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR_FULL_PATH}"

${MKDIR} -p "${YERITH_BULLSEYE_I386_PACKAGE_DIR_FULL_PATH}"

ORIGINAL_PWD=$(pwd)

#cd "${YERITH_ERP_3_0_HOME_FOLDER}/yerith-erp-3-0-development-scripts"
#./yerith-create-dpkg_yerith-erp-3-0-standalone.sh
#cd "${ORIGINAL_PWD}"

${CP} ${HOME}/CACHE-YR-JHNISSI-DEBIAN-PACKAGES/*.deb ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_SYSTEM_DAEMON_HOME_FOLDER}/yerith-erp-3-0-system-daemon.deb ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_SYSTEM_DAEMON_HOME_FOLDER}/yerith-erp-3-0-system-daemon-I386.deb ${YERITH_BULLSEYE_I386_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_HOME_FOLDER}/yerith-erp-3-0-standalone.deb ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_HOME_FOLDER}/yerith-erp-3-0-standalone-ENGLISH.deb ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_HOME_FOLDER}/yerith-erp-3-0-standalone-configurations-data.deb ${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_HOME_FOLDER}/yerith-erp-3-0-standalone-configurations-data-ENGLISH.deb ${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_HOME_FOLDER}/yerith-erp-3-0-standalone-I386.deb ${YERITH_BULLSEYE_I386_PACKAGE_DIR_FULL_PATH}

${CP} ${YERITH_ERP_3_0_HOME_FOLDER}/yerith-erp-3-0-standalone-ENGLISH-I386.deb ${YERITH_BULLSEYE_I386_PACKAGE_DIR_FULL_PATH}

cd "${YERITH_VAR_WWW_HTML_DEBIAN_REPO}"

dpkg-scanpackages ${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR} > ${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR}/Packages
dpkg-scanpackages ${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR} | ${GZIP} > ${YERITH_BULLSEYE_ARCH_ALL_PACKAGE_DIR}/Packages.gz

dpkg-scanpackages ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR} > ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR}/Packages
dpkg-scanpackages ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR} | ${GZIP} > ${YERITH_BULLSEYE_AMD64_PACKAGE_DIR}/Packages.gz

dpkg-scanpackages ${YERITH_PACKAGE_DIR} > ${YERITH_PACKAGE_DIR}/Packages
dpkg-scanpackages ${YERITH_PACKAGE_DIR} | ${GZIP} > ${YERITH_PACKAGE_DIR}/Packages.gz

cd "${ORIGINAL_PWD}"

